// Shared data for both variants
window.MM_DATA = {
  artist: {
    name: "Raven Crochês",
    handle: "@r4ven.vmp",
    igUrl: "https://www.instagram.com/r4ven.vmp/",
    waUrl: "https://wa.me/556293736614",
    tagline: "amigurumis & croché com alma",
    sub: "feito à mão por uma estudante de arte do IFG — cada peça carrega um pedacinho de mim.",
  },
  pricing: {
    headline: "preço justo, feito a mão",
    formula: "R$15 / hora de trabalho + custo da linha",
    note: "cada peça leva de 3 a 15 horas — o valor varia por tamanho, complexidade e cores.",
  },
  // Featured hero — pixel art of the artist
  featured: {
    name: "Raven",
    note: "fio, lua e atitude",
    year: "lua cheia ⋅ pixel art",
    type: "bat",
  },
  // Real products with photos
  creatures: [
    {
      id: "salem",
      name: "Salem",
      kind: "gatinho de gola",
      priceFrom: 140,
      hours: "~ 9h",
      photo: "assets/produto-gato.jpg",
      type: "cat",
      color: "#0a0a0f",
      note: "olhos enormes, alma de bruxo",
      desc: "amigurumi de gato preto em fio chenille (felpudinho), olhos bordados em amarelo, golinha branca. tem braços e pernas articulados que abraçam.",
      size: "~ 28cm",
      yarn: "fio chenille premium",
    },
    {
      id: "medusa",
      name: "Medusa",
      kind: "água-viva flutuante",
      priceFrom: 95,
      hours: "~ 5h",
      photo: "assets/produto-aguaviva.jpg",
      type: "octopus",
      color: "#7a5fb0",
      note: "feita pra pendurar e balançar",
      desc: "água-viva de croché com tentáculos longos em fio crú e lilás. linda pendurada no teto do quarto ou na janela.",
      size: "~ 35cm com tentáculos",
      yarn: "fio cisne 100% algodão",
    },
    {
      id: "yuki",
      name: "Touca Yuki",
      kind: "touca de orelhinha + laço",
      priceFrom: 75,
      hours: "~ 4h",
      photo: "assets/produto-toucagato.jpg",
      type: "cat",
      color: "#f6f4ef",
      note: "kawaii até no inverno",
      desc: "touca em ponto baixo com orelhinhas de gatinho e laço aplicado. branca com laço vermelho — escolha sua combinação.",
      size: "tamanhos P/M/G",
      yarn: "fio cisne 100% algodão",
    },
    {
      id: "moranguinho",
      name: "Top Moranguinho",
      kind: "top frutinha",
      priceFrom: 110,
      hours: "~ 7h",
      photo: "assets/produto-top-morango.jpg",
      type: "bunny",
      color: "#c41e3a",
      note: "verão eterno",
      desc: "top de croché vermelho com babado verde em formato de morango. amarração no pescoço e nas costas, tamanho sob medida.",
      size: "sob medida",
      yarn: "barbante cor sólida",
    },
    {
      id: "reggae",
      name: "Conjunto Reggae",
      kind: "biquíni + saída",
      priceFrom: 240,
      hours: "~ 14h",
      photo: "assets/produto-bikini-reggae.jpg",
      type: "ghost",
      color: "#1a8b4a",
      note: "verão & sound system",
      desc: "conjunto completo: top de biquíni com as cores rasta + saída de praia em ponto vazado preta com listras vermelho/amarelo/verde. botões funcionais.",
      size: "sob medida",
      yarn: "barbante de algodão",
    },
    {
      id: "sob-encomenda",
      name: "Sua peça",
      kind: "criação sob medida",
      priceFrom: null, // special card
      hours: "a combinar",
      photo: null, // will render the bat creature SVG
      type: "bat",
      color: "#1a0a14",
      note: "manda referência, eu rascunho",
      desc: "tem uma ideia na cabeça? me chama no instagram com referências, fotos, ou só descreve a vibe. eu rascunho, a gente conversa, ajusta e construo.",
      size: "varia",
      yarn: "varia",
      isCustom: true,
    },
  ],
  testimonials: [
    { name: "Júlia P.", piece: "Salem", text: "chegou embaladinho com bilhete escrito à mão, chorei na hora que abri. é arte mesmo.", city: "Goiânia" },
    { name: "Rafa M.", piece: "Touca Yuki", text: "encomendei pra minha namorada de aniversário e ela usa toda semana. obrigado Raven!!", city: "Aparecida" },
    { name: "Bia T.", piece: "Conjunto Reggae", text: "eu queria algo bem específico, mandei mil referências e a Raven entregou EXATAMENTE. ela escuta de verdade.", city: "Brasília" },
    { name: "Drê V.", piece: "Medusa", text: "a qualidade do trabalho é absurda. ponto perfeito, nada solto. e a água-viva fica linda pendurada no quarto!", city: "São Paulo" },
    { name: "Mari L.", piece: "Top Moranguinho", text: "comprei um top, depois encomendei outro, depois mais um. é vício. socorro.", city: "Goiânia" },
  ],
  process: [
    { n: "01", title: "a conversa", text: "tudo começa no DM. me conta o que quer, manda referência, descreve a vibe. eu pergunto bastante." },
    { n: "02", title: "o orçamento", text: "estimo as horas + custo da linha e te mando o valor antes de começar. tudo transparente." },
    { n: "03", title: "o feitiço", text: "ponto por ponto, em geral 3 a 15 horas de trabalho. mando foto do processo se você quiser ver crescendo." },
    { n: "04", title: "a entrega", text: "embalada em saquinho de cetim com bilhete escrito à mão. envio pra todo Brasil." },
  ],
};
